### ISSUE TITLE
Notifications: Numbers increasing even when viewing those notifications (not going back to 0)

### ISSUE THREAD

**Issue by msilbers** [woocommerce/woocommerce-ios#2663]
**Describe the bug**
We've had 3 reports so far of folks seeing numbers only increasing for the notification bubble/alert. For example, if they have a notification of 12 new orders and check them, so it disappears, the next order then brings it to 13 instead of 1, or some much larger number. Some folks are describing it a bit differently though.

> My app’s notification number never matches anything in particular, in this case I have 28 new orders and the app showed 69 notifications. 

> The number is not right. It currently says 215 but I only have 1 order.
I have seen it go higher by large amounts with each new order

> So like I’ll have 22 orders, fulfill one, the badge counter disappears like I wanted it to before....but when the next order comes in, the badge comes up as 23 instead of 1.

**To Reproduce**

I'm unable to reproduce this myself, but from the reports:

1. Check your notifications for the app to clear them out
2. Receive a new order
3. Check the number shown in the notification alert/bubble
4. It may not correspond with either new notifications or existing ones

**Screenshots**

![2F1169DB-430F-4D71-B55B-9E4AD7DF24D1_L0_001](https://user-images.githubusercontent.com/31680407/90340574-24605380-dfc7-11ea-83e4-ac0b7e1e2be6.jpeg)
![ACE987ED-947C-4C09-AED7-82A05BBADF6E_L0_001](https://user-images.githubusercontent.com/31680407/90340575-25918080-dfc7-11ea-90a7-02c8ded849a2.jpeg)

**Expected behavior**
I expect that when checking the order or opening the app and seeing the notifications, that the next incoming one will add 1 to the alert, which is the behavior I see when trying to replicate this.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**

- Device: iPhone 11,2
- iOS version: 13.6
- WooCommerce iOS version: 4.6.0.2

---

- Device: iPhone 12,1
- iOS version: 13.6
- WooCommerce iOS version: 4.7.0.4 ("Also I did update to 4.7 yesterday and this was happening before and it still is with the update.")

---

- Device: iPhone 8,2
- iOS version: 13.6
- WooCommerce iOS version: 4.6.0.2

reported internally in 3229034-zen, 3225184-zen, 3230531-zen

**Comment by astralbodies** [comment]
Still noodling on this issue - it will be a server-side fix. We share the push notification system for WordPress.com. I suspect these users are probably not using the WordPress iOS app and therefore the "unread count" is never being reset. The Woo app never resets the unread count because it only uses a subset of notifications from WordPress.com in the app; resetting the unread count would cause side effects in the WordPress app. There was a bug in the server-side code that I mentioned earlier that I fixed where Woo notifications were being dismissed when read on another device or if WPiOS was left on the notifications screen when backgrounded (there's a bug in that app). That was masking the fact that the badge count on Woo iOS was never really being reset. The badge count also should really be a sum of orders to fulfill + unapproved or new product reviews (the two places in the app that show counts). Getting that count on the server-side is difficult / slow so I'm not entirely sure what the right course of action is here. I may end up setting the badge count to 1 whenever there's a new notification instead of trying to come up with a number that'll end up being inaccurate anyway. Android has it easier - the app icon just shows a dot when there's a new notification. 🙃

**Comment by rachelmcr** [comment]
A beta tester using the 5.0 TestFlight beta reported this issue persisting for them:

> Hi, still experiencing badge notification weirdness. Let’s say on the first day after installing the app, I receive an order. The badge says “1” until I complete the order and visit the Orders tab. Then, I get another order. There’s only 1 order in processing, but the badge says 2. So after clearing the badge and getting new orders, the badge always wrongfully reflects TOTAL ORDERS SINCE INSTALLING APP, not the expected, total number of incomplete orders right now.

I don't think that reports tells us anything new, or helps decide on a solution, but wanted to note it for reference and also mention it in case there's anything that you think it would help to have beta testers involved in.

**Comment by rachelmcr** [comment]
I'd forgotten this was still an issue and just want to note I'm still seeing it as of the 5.4.0.1 TestFlight beta. (Noticed while testing various push notification scenarios.)

**Comment by astralbodies** [comment]
I'm deploying a fix server-side shortly to set the badge count to `1` for every push as a fix until we can figure out what makes the most sense for our users. There are some system limitations with how the pushes currently work, so I'd rather address the ugliest issue with the incrementing count for those users with multiple iOS devices.
